<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\RabbitMq.Domain\RabbitMq.Domain.csproj" />
      <ProjectReference Include="..\RabbitMq.Persistence\RabbitMq.Persistence.csproj" />
    </ItemGroup>

</Project>
